[project]
name = "product-query-gen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.118.0",
    "openai>=2.0.0",
    "uvicorn>=0.37.0",
]
